# Generated by Django 5.2.6 on 2025-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_remove_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('date_earned', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('certificate_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='certificate/')),
            ],
        ),
    ]
