# Generated by Django 5.2.6 on 2025-09-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='subject1',
        ),
    ]
