# Generated by Django 6.0.5 on 2026-06-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0005_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
